-- Hand-written migration, applied manually (never drizzle-kit push/generate).
--
-- STATUS (2026-09-09): successfully applied to production. A first attempt
-- (2026-09-06) was ABORTED mid-way (`KILL <id>` on the ALTER) - real
-- disk I/O contention with live traffic, compounded by a concurrent
-- watchdog script that was independently killing the app's own DB
-- connections (a separate, self-inflicted mistake - see PLAN.md's
-- "genuinely bad hour" writeup). Re-attempted 2026-09-09 during a
-- deliberately monitored window (load average/iostat checked before and
-- throughout, `curl` health checks against the live site during the
-- build) and completed cleanly, confirmed via `SHOW INDEX FROM book`.
-- `fetchCategoryPage`'s "tr" bucket now actually uses this index (see its
-- own updated comment) - this migration is no longer inert.
--
-- Same disease as 0043's idx_book_lang_score, for `getBooksByCategory`'s
-- Turkish/non-Turkish category-listing split (books.ts) instead of
-- "Benzer Kitaplar" - confirmed live that category 31's Turkish bucket
-- (882 of 2,215,001 total books, real view_count values 0-1) made the
-- book-first global-view_count-order plan walk deep into the 98.5M-row
-- table trying to find enough Turkish matches, timing out past 120s live.
-- Bounds that walk by Turkish's own ~126K-book population instead.
ALTER TABLE book ADD INDEX idx_book_lang_viewcount (lang, view_count), ALGORITHM=INPLACE, LOCK=NONE;
